# Generated by Django 4.1 on 2022-08-11 21:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('synopsis', models.TextField(max_length=1000)),
                ('genre', models.CharField(choices=[('RG', 'Religioso'), ('AC', 'Accion'), ('DR', 'Drama'), ('CM', 'Comedia'), ('SF', 'Ciencia Ficcion'), ('THR', 'Triler')], default='', max_length=155)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movies', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
