# Generated by Django 4.1 on 2022-08-09 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_movie_cast_remove_movie_genre'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cast',
        ),
        migrations.DeleteModel(
            name='Genre',
        ),
    ]
