# Generated by Django 4.1 on 2022-08-09 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_movie_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.CharField(choices=[('RG', 'Religioso'), ('AC', 'Accion'), ('DR', 'Drama'), ('CM', 'Comedia'), ('SF', 'Ciencia Ficcion'), ('THR', 'Triler')], default='', max_length=155),
        ),
    ]
